services:
  - type: web
    name: ubuntu-novnc-gui
    env: docker
    dockerfilePath: ./Dockerfile
    plan: standard
    instanceType: free
    envVars:
      - key: VNC_PASSWD
        value: "123456"
      - key: PORT
        value: "10000"
      - key: VNC_PORT
        value: "5900"
      - key: WEBSOCKIFY_PORT
        value: "6900"
      - key: AUDIO_PORT
        value: "1699"
      - key: SCREEN_WIDTH
        value: "1024"
      - key: SCREEN_HEIGHT
        value: "768"
      - key: SCREEN_DEPTH
        value: "24"
    healthCheckPath: /
    autoDeploy: true
